### PR TITLE
Latest typescript update (typescript@1.6.0-dev.20150802) now emits '.jsx' files for '.tsx'.

### PR DESCRIPTION
**Pull request by wwwsevolod**

### CODE REVIEW

**Comment by wwwsevolod** [comment]
Hello there! Thank you for great loader. Hope you'll accept this changes as soon as possible.
i had an hour of WTF, 'WHY MY CODE IS NOT EMIT OUTPUT'

**Comment by s-panferov** [comment]
Oops, I've tested this version today but not with .tsx. I'll be near PC to publish new version in 30min

**Comment by s-panferov** [comment]
@wwwsevolod landed as v0.11.1. Thanks for the PR.

**Comment by wwwsevolod** [comment]
Thank you!

**Pull request merged**
