### PR TITLE
customTranformersPath

### PR DESCRIPTION
**Pull request by goloveychuk**
Since with `CheckerPlugin` checker starting in forked process, it's impossible to pass function as an argument.
The solution could be to pass customTransformer as a module path.

### CODE REVIEW

**Comment by goloveychuk** [comment]
actually we can reproduce webpack2 behaviour
```
/webpack
     /config.js
     /mycustom-loader.js
```

in config.js
```js
const config = {
   use: [
         { loader: 'mycustom-loader', options: {} }
   ]
}
```

So webpack resolves loaders relatively for webpack root.
Same could be done for atl

**Comment by goloveychuk** [comment]
actually, easiest way to go:
```js
use: [
      {
        loader: 'awesome-typescript-loader',
        options: {
          customTranformersPath: require.resolve('./ts_transformers'),
        }
      }
    ]
```

**Comment by Igorbek** [comment]
I would suggest to change required shape of a module being treated as custom transformers configuration. 

I have two considerations:
1. returning a function making impossible to use es modules
2. constraining to just a single function prevents further extending if we need more complex objects/functions passed down to forked processes.

My proposal is the following:

1. Add the following option:

```ts
export interface LoaderConfig {
    optionsModule?: string;
}
```

2. Forked process as well as in-proc version, would resolve the module, if it is specified, and would expect the following module shape:

```ts
export interface OptionsModule {
    options?: {
        getCustomTransformers?(): ts.CustomTransformers | undefined;
    };
}
```

it would allow such modules be extended in the future with something related to options as well as something unrelated.

**Comment by goloveychuk** [comment]
@Igorbek 
it would make more difficult to setup ATL for other users, who don't use customTransformers.
Or it could support 2 ways. But this, really, don't look "webpack way".
So when you look at webpack.config, you should see whole configuration, explicitly. When you have path to config - it makes understanding harder.

**Comment by Igorbek** [comment]
Oh, I'm not suggesting to replace configuration altogether with that. I'm saying that the module should be able to widened in the purpose in the future. To not restrict ourselves to one single option.

**Pull request closed without merging**
