### PR TITLE
Feature/debounce fork checker

### PR DESCRIPTION
**Pull request by nik-kor**
This PR should be merged after https://github.com/s-panferov/awesome-typescript-loader/pull/91 .
So the real changes is in 938fc96

### CODE REVIEW

**Comment by s-panferov** [comment]
@nik-kor 	did you faced with an issue with the checker? Why do you think you need debounce here? I believe, that debouncing already implemented at webpack's watching level. Or I'm missing something?

**Comment by nik-kor** [comment]
Webpack's watching is very sensitive. So it will start checker on every change. I found it useless and annoying, you know, then checker runs on every change - and you see a sequence of checks.

Maybe it depends on the style of writing code or how the code editor handle changes and it's my only problem. But anyway I think that debouncing is worth here.

**Comment by nik-kor** [comment]
Oh, you can run tests to be sure

**Comment by s-panferov** [comment]
@nik-kor 	ok, sounds good. Thanks!

**Pull request merged**
