### PR TITLE
add failOnTypeErrors option

### PR DESCRIPTION
**Pull request by gipsy-king**
grunt-ts has a "failOnTypeErrors" which is very nice when you are transitioning a project to typescript.
This PR adds an option, disabled by default, that allows to compile and generate output if there are only errors that aren't syntax or compiler flag errors - they are assumed to be type errors. For these errors only warnings will be emitted.

### CODE REVIEW

**Comment by s-panferov** [comment]
@gipsy-king hello. Thanks for your PR. But I believe that v0.3.0 already addresses your needs. Error reporting was significantly redesigned there (it doesn't fail now by default, but I'll add the 'failOnTypeErrors' in the future). Please try and say what do you think.

**Comment by gipsy-king** [comment]
"just-emit" sounds like what I want, let me test and report back. Thanks!

**Comment by gipsy-king** [comment]
Is there a problem with the npm module? It looks like it doesn't have `dist/` included, I can't use the loader unless I enter `node_modules/awesome-typescript-loader` and run `npm install` and then `grunt`.

Apart from that, it does almost exactly what I wanted. The only thing that would be nice, would be an option to turn off the `console.error` messages that are added to the generated files (if you want to build for production).

**Comment by s-panferov** [comment]
@gipsy-king an issue with /dist was fixed in v0.3.1, thanks for reporting!

> The only thing that would be nice, would be an option to turn off the console.error messages that are added to the generated files

I think that this makes sense. I'll try to make this today or tomorrow (GMT+3).

**Comment by gipsy-king** [comment]
Awesome, thank you!

**Pull request closed without merging**
